// File generated by FlutterFire CLI.
// Run `flutterfire configure` to replace placeholder values with your project config.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg71LjopjMXPy-EcSW3nAVeBMdCvRBnJ0',
    appId: '1:892173139237:web:67d54f42812ea78bb96ecc',
    messagingSenderId: '892173139237',
    projectId: 'ca-global-leave-portal',
    authDomain: 'ca-global-leave-portal.firebaseapp.com',
    storageBucket: 'ca-global-leave-portal.firebasestorage.app',
    measurementId: 'G-3EYTWNZV97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_rRLWzPrX1P3eHWSYZjP5POZeSS84RY',
    appId: '1:892173139237:android:eb904cf032ad8a9bb96ecc',
    messagingSenderId: '892173139237',
    projectId: 'ca-global-leave-portal',
    storageBucket: 'ca-global-leave-portal.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.caglobal.hrPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.caglobal.hrPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg71LjopjMXPy-EcSW3nAVeBMdCvRBnJ0',
    appId: '1:892173139237:web:426653a115dc0264b96ecc',
    messagingSenderId: '892173139237',
    projectId: 'ca-global-leave-portal',
    authDomain: 'ca-global-leave-portal.firebaseapp.com',
    storageBucket: 'ca-global-leave-portal.firebasestorage.app',
    measurementId: 'G-JMS6YCPS88',
  );
}
